# Timeout in seconds that Limine will use before automatically booting.
TIMEOUT=3

# The entry name that will be displayed in the boot menu.
/Limine Template
    # We use the Limine boot protocol.
    PROTOCOL: limine

    # Disable KASLR (it is enabled by default for relocatable kernels)
    KASLR: no

    # Path to the kernel to boot. boot:/// represents the partition on which limine.cfg is located.
    KERNEL_PATH: boot():/boot/kernel
    KERNEL_CMDLINE: root_drive_guid=6A7A6FB8-26BF-4080-973A-3BF1DE1B86D4 root_partition_guid=63482341-8441-4F39-927F-3832A6DBE78C

# Same thing, but with KASLR.
/Limine Template (with KASLR)
    PROTOCOL: limine

    KERNEL_PATH: boot():/boot/kernel
    KERNEL_CMDLINE: root_drive=0 root_entry=0
